apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: slm-inference
spec:
  to:
    kind: Service
    name: slm-inference
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
